url: https://jinghuizhao.github.io
#baseurl: /arbosteun/

# Site settings
title: Jinghui Zhao
email: jzhao54@usfca.edu
description: "I do data science"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: 
# Postal address (add as many lines as necessary)
address:
  - line: 155 Jackson Street
  - line: San Francisco, 94111

# Build settings
markdown: kramdown
permalink: pretty
